addr: :8181

auth:
  enabled: false
  username: admin
  password: admin

log:
  level: info

monitor:
  rate: 5          # seconds

process:
  pid_file: ./../app.pid

security:
  encryption_key: 8FVKXDQxzgdEH8DR8wQPnCo6Ke5IwQ+CYdqdmjmi/Lk=

https:
  enabled: false
  cert_path: conf/cert.pem
  key_path: conf/key.pem

managed_apps: []
